### PR TITLE
outline lightened

### PR DESCRIPTION
**Pull request by dougmcg**
The level of grey is bumped up a bit to make the falcon more visible.

### CODE REVIEW

**Review by MiloCS — APPROVED** [review]
Seems good.

**Comment by dougmcg** [comment]
Thanks Milo. I'm looking to hear from all three of you. Here are a couple of images to use for comparison:
image
image

Milo - feel free to change your vote given this side by side comparison.

**Review by maxtkc — APPROVED** [review]
It looks good. Is there any way we can get slightly better quality? Smooth the edges?

**Review by Dinavoevodsky — APPROVED** [review]
Looks good! I agree with Max that a little better quality would be ideal but other than that it's great!

**Pull request merged**
