### PR TITLE
Streamline schedules

### PR DESCRIPTION
**Pull request by psvenk**
This pull request addresses issue #35.
- Changed schedules to be nested arrays instead of arrays of objects (for performance and concision reasons)
- Changed some functions to properly deal with the new schedule format
- Made indentation consistent with the schedules (2 spaces, the same as most of the rest of the code base)
- Add April Vacation and black days for April

The new code doesn't use any somewhat recent JavaScript features, so it should not break compatibility with older browsers. This code has only been tested on the latest version of Chromium (Chrome) on GNU+Linux at the time of writing.

Here is a link so that you can test the new code: https://derp7777.github.io/CRLSTime/web/streamline-schedules/

### CODE REVIEW

**Comment by psvenk** [comment]
This new code seems to be working on modern browsers (I am testing on Safari 12.0.3 on macOS Mojave right now). I'll post screenshots once the school day has finished. I don't think there are any advanced features added in this PR, so this should presumably work on older browsers if it works on modern browsers. You may want to check on an older browser just in case (I don't have access to very old browsers right now).

**Comment by psvenk** [comment]
I think this is now ready to merge @dougmcg. Here are some screenshots, some on the latest Safari and some on an older Firefox:

Screen Shot 2019-04-29 at 9 04 22 AM Screen Shot 2019-04-29 at 9 25 44 AM Screen Shot 2019-04-29 at 9 37 15 AM Screen Shot 2019-04-29 at 9 38 38 AM Screen Shot 2019-04-29 at 9 43 30 AM Screen Shot 2019-04-29 at 9 45 58 AM Screen Shot 2019-04-29 at 9 46 03 AM Screen Shot 2019-04-29 at 9 48 48 AM Screen Shot 2019-04-29 at 10 00 15 AM Screen Shot 2019-04-29 at 10 48 43 AM Screen Shot 2019-04-29 at 11 30 24 AM Screen Shot 2019-04-29 at 11 30 33 AM Screen Shot 2019-04-29 at 11 30 37 AM

**Comment by psvenk** [comment]
Please note that the black days and holidays that I just added are part of the pull request and will show up in the mainline CRLSTime once this is merged, but it doesn’t yet show up in <https://derp7777.github.io/CRLSTime/web/streamline-schedules/> because I am away from my home computer which is where I update that site. You are free to clone the `streamline-schedules` branch of Derp7777’s fork if you want assurance that these are not breaking changes.

**Review by dougmcg — APPROVED** [review]
Going to merge this now.

**Pull request merged**
