### PR TITLE
Added Local Storage abilities for lunch

### PR DESCRIPTION
**Pull request by maxtkc**
I am requesting that you pull this branch.
It is very good.
It should work.
It saves the lunch to `document.localStorage`

### CODE REVIEW

**Review by dougmcg — CHANGES_REQUESTED** [review]
I'm pretty sure this won't work as it is. The variable schedule needs to be linked to lunchMode. It looks like line 274 of your branch always sets schedule to scheduleA regardless of lunchMode...

**Comment by maxtkc** [comment]
I think that I need edit access to push to this branch. I did make some changes that fix this bug.

**Comment by maxtkc** [comment]
This link explains the various permission levels:
https://help.github.com/articles/repository-permission-levels-for-an-organization/
What you could do is give write permissions to people and then protect the branches that are created so that they can only be merged by you. You could protect master as well.

This is only available to Admin and Owner as shown in the table:
> Merge pull requests on protected branches, even if there are no approved reviews

**Comment by dougmcg** [comment]
Max, I think you should have the access you need now to commit new code to this branch... yes?

**Comment by maxtkc** [comment]
I made the changes to line 274, although I pushed under the wrong username again... that's my other account, I think that these permissions are working well.

**Comment by dougmcg** [comment]
Did you decide not to use "===" ?

**Comment by dougmcg** [comment]
Max - I'd like to merge this but there are a couple issues. Two binary files were added in your commit. I might be able to delete them, but I can't figure out how. Can you remove them from the commit? Also, can you revise your most recent commit so it uses "===" instead of "==". I think we want the triple version, yes?

**Comment by maxtkc** [comment]
When this is merged with the other branches, I think that the changing the == to === will carry over, as long as there are no issues with merging due to changing the same part of the code in different branches.

**Comment by dougmcg** [comment]
So you are thinking that your new lines 277, 279, and 281 will be converted to using triple equal signs?

**Comment by scornman** [comment]
It looks to me like the getSchedule method is new in this commit, so the merge won't affect the == inside it. The == in the parts of the code you didn't change will be fine, but you will need to change the ones you moved into the getSchedule method, since git probably isn't smart enough to account for that.

EDIT: Sorry for the duplicate comment.

**Comment by maxtkc** [comment]
How do we resolve the conflicts? I don't exactly understand what the conflict is.

**Pull request merged**
